package com.gwidgets.example.client;


import com.google.gwt.core.client.EntryPoint;




public class GwtDiDagger implements EntryPoint {
	
  public void onModuleLoad() {
	  
	  //don't worry of the IDE complains about DaggerAppComponent, it is generated by the dagger comppiler
//	  AppComponent component = DaggerAppComponent.builder()
//				.mVPModule(new MVPModule())
//				.build();
	  
	  AppComponent component = DaggerAppComponent.builder()
			                   .imageCompressionModule(new ImageCompressionModule())
			                   .build();
	  
	  component.getImageCompressor().compress("http://www.g-widgets.com/GWTcon.jpg");
		        
  }
}
